[project]
name = "wxread"
version = "2.0.0"  # 修改: "0.1.0" -> "2.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.13.0",
]
